# Generated by Django 2.2.5 on 2019-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('division', models.CharField(max_length=50)),
                ('addrs', models.CharField(max_length=50)),
            ],
        ),
    ]
