# Generated by Django 3.0.3 on 2020-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('delimeter', models.CharField(max_length=100)),
                ('encode', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('sub_catagory', models.CharField(max_length=100)),
            ],
        ),
    ]
